"""Add history column to game model

Revision ID: 2865ec28e2b6
Revises: fd7f9f1bb17f
Create Date: 2025-10-04 14:26:38.649105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2865ec28e2b6'
down_revision = 'fd7f9f1bb17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('history')

    # ### end Alembic commands ###
