"""create users table

Revision ID: 510dc30935ed
Revises: d092260084d7
Create Date: 2025-10-03 13:53:44.459999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510dc30935ed'
down_revision = 'd092260084d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('captured_white', sa.Integer(), nullable=False),
    sa.Column('captured_black', sa.Integer(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('won_by', sa.String(length=20), nullable=True),
    sa.Column('opponent_type', sa.String(length=20), nullable=False),
    sa.Column('board_size', sa.Integer(), nullable=False),
    sa.Column('board_state', sa.JSON(), nullable=False),
    sa.Column('current_turn', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
