"""adadd move model

Revision ID: bf9b1008bcc3
Revises: 510dc30935ed
Create Date: 2025-10-03 21:49:01.894467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9b1008bcc3'
down_revision = '510dc30935ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_color', sa.String(length=10), nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('captures_black', sa.Integer(), nullable=True),
    sa.Column('captures_white', sa.Integer(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('move_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    # ### end Alembic commands ###
